<div class="slide-container slider-4">
    <div id="rev_slider_10_1_wrapper" class="rev_slider_wrapper fullscreen-container" style="background-color:transparent;padding:0px;">
        <div id="rev_slider_10_1" class="rev_slider fullscreenbanner" style="display:none;" data-version="5.2.6">
            <ul>
                <li data-index="rs-58" data-transition="random" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/next-page-01-285x52.png" data-delay="7019.6875" data-rotate="0" data-fstransition="fade" data-fsmasterspeed="300" data-fsslotamount="7" data-saveperformance="off" class="style-slider-4" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <img src="wp-content/plugins/revslider/admin/assets/images/dummy.png" alt="" title="Home" data-lazyload="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/background-imageslider-1.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-first" id="slide-58-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','50','28','14']" data-y="['top','top','top','top']" data-voffset="['270','187','203','150']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1330;e:Power3.easeInOut;" data-transform_out="x:left;skX:45px;s:640;" data-start="-0.625" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6149.375" style="z-index: 5; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 300; color: rgba(255, 255, 255, 1.00);text-transform:left;">TAKE WATER </div>
                    <div class="tp-caption   tp-resizeme  iw-slider-1-to" id="slide-58-layer-6" data-x="['left','left','left','left']" data-hoffset="['0','53','30','15']" data-y="['top','top','top','top']" data-voffset="['335','296','278','201']" data-fontsize="['30','26','26','16']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:left;s:380;e:Power3.easeInOut;" data-transform_out="x:left;s:600;e:Power3.easeInOut;" data-start="1600" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6360" style="z-index: 6; white-space: nowrap; font-size: 30px; line-height: 24px; font-weight: 700; color: rgba(255, 255, 255, 1.00);text-transform:left;">TO </div>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-default" id="slide-58-layer-4" data-x="['left','left','left','left']" data-hoffset="['61','100','79','41']" data-y="['top','top','top','top']" data-voffset="['345','292','263','184']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-fontweight="['400','900','900','900']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;rZ:inherit;" data-transform_in="x:right;s:520;e:Power3.easeInOut;" data-transform_out="x:right;skX:-85px;s:170;" data-start="1860" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6580" style="z-index: 7; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 400; color: rgba(255, 255, 255, 1.00);text-transform:left;">AROUND THE WORLD </div>
                </li>
                <li data-index="rs-59" data-transition="random" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/next-page-02-285x52.png" data-delay="7019.6875" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <img src="wp-content/plugins/revslider/admin/assets/images/dummy.png" alt="" title="Home" data-lazyload="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/about_education_above_all.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-first" id="slide-59-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','50','28','14']" data-y="['top','top','top','top']" data-voffset="['270','187','203','150']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1330;e:Power3.easeInOut;" data-transform_out="x:left;skX:45px;s:640;" data-start="-0.625" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6149.375" style="z-index: 5; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 300; color: rgba(255, 255, 255, 1.00);text-transform:left;">EMPOWER CHILDREN </div>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-default" id="slide-59-layer-4" data-x="['left','left','left','left']" data-hoffset="['1','100','79','41']" data-y="['top','top','top','top']" data-voffset="['347','292','263','184']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-fontweight="['400','900','900','900']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;rZ:inherit;" data-transform_in="x:right;s:520;e:Power3.easeInOut;" data-transform_out="x:right;skX:-85px;s:170;" data-start="1860" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6580" style="z-index: 6; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 400; color: rgba(255, 255, 255, 1.00);text-transform:left;">THROUGH EDUCATION </div>
                </li>
                <li data-index="rs-60" data-transition="random" data-slotamount="7" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/next-page-03-285x52.png" data-delay="7019.6875" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="">
                    <img src="wp-content/plugins/revslider/admin/assets/images/dummy.png" alt="" title="Home" data-lazyload="http://inwavethemes.com/wordpress/incharity/wp-content/uploads/revslider/slider-4/education_above_all_children_v2.jpg" data-bgposition="center top" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg" data-no-retina>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-first" id="slide-60-layer-2" data-x="['left','left','left','left']" data-hoffset="['0','50','28','14']" data-y="['top','top','top','top']" data-voffset="['270','187','203','150']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;" data-transform_in="x:-50px;opacity:0;s:1330;e:Power3.easeInOut;" data-transform_out="x:left;skX:45px;s:640;" data-start="-0.625" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6149.375" style="z-index: 5; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 300; color: rgba(255, 255, 255, 1.00);text-transform:left;">URGENT PROJECTS </div>
                    <div class="tp-caption   tp-resizeme  iw-slider-home-default" id="slide-60-layer-4" data-x="['left','left','left','left']" data-hoffset="['-2','100','79','41']" data-y="['top','top','top','top']" data-voffset="['346','292','263','184']" data-fontsize="['60','50','40','25']" data-lineheight="['24','50','60','60']" data-fontweight="['400','900','900','900']" data-width="none" data-height="none" data-whitespace="nowrap" data-transform_idle="o:1;rZ:inherit;" data-transform_in="x:right;s:520;e:Power3.easeInOut;" data-transform_out="x:right;skX:-85px;s:170;" data-start="1860" data-splitin="none" data-splitout="none" data-responsive_offset="on" data-end="6580" style="z-index: 6; white-space: nowrap; font-size: 60px; line-height: 24px; font-weight: 400; color: rgba(255, 255, 255, 1.00);text-transform:left;">SUCCESS STORIES </div>
                    
                </li>
            </ul>
            <script>var htmlDiv=document.getElementById("rs-plugin-settings-inline-css");var htmlDivCss="";if(htmlDiv){htmlDiv.innerHTML=htmlDiv.innerHTML+htmlDivCss;}else{var htmlDiv=document.createElement("div");htmlDiv.innerHTML="<style>"+htmlDivCss+"</style>";document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);}</script>
            <div class="tp-bannertimer tp-bottom" style="visibility: hidden !important;"></div>
        </div>
        <script>var htmlDiv=document.getElementById("rs-plugin-settings-inline-css");var htmlDivCss="";if(htmlDiv){htmlDiv.innerHTML=htmlDiv.innerHTML+htmlDivCss;}else{var htmlDiv=document.createElement("div");htmlDiv.innerHTML="<style>"+htmlDivCss+"</style>";document.getElementsByTagName("head")[0].appendChild(htmlDiv.childNodes[0]);}</script>
        <script type="text/javascript">var setREVStartSize=function(){
                try{
                    var e=new Object,
                        i=jQuery(window).width(),
                        t=9999,r=0,n=0,l=0,f=0,s=0,h=0;e.c=jQuery('#rev_slider_10_1');
                    e.responsiveLevels=[1240,1024,778,480];
                    e.gridwidth=[1170,1024,767,479];
                    e.gridheight=[625,600,500,400];e.sliderLayout="fullscreen";
                    e.fullScreenAutoWidth='off';e.fullScreenAlignForce='off';
                    e.fullScreenOffsetContainer='';e.fullScreenOffset='';if(e.responsiveLevels&&(jQuery.each(e.responsiveLevels,function(e,f){f>i&&(t=r=f,l=e),i>f&&f>r&&(r=f,n=e)}),t>r&&(l=n)),f=e.gridheight[l]||e.gridheight[0]||e.gridheight,s=e.gridwidth[l]||e.gridwidth[0]||e.gridwidth,h=i/s,h=h>1?1:h,f=Math.round(h*f),"fullscreen"==e.sliderLayout){var u=(e.c.width(),jQuery(window).height());if(void 0!=e.fullScreenOffsetContainer){var c=e.fullScreenOffsetContainer.split(",");if(c)jQuery.each(c,function(e,i){u=jQuery(i).length>0?u-jQuery(i).outerHeight(!0):u}),e.fullScreenOffset.split("%").length>1&&void 0!=e.fullScreenOffset&&e.fullScreenOffset.length>0?u-=jQuery(window).height()*parseInt(e.fullScreenOffset,0)/100:void 0!=e.fullScreenOffset&&e.fullScreenOffset.length>0&&(u-=parseInt(e.fullScreenOffset,0))}f=u}else void 0!=e.minHeight&&f<e.minHeight&&(f=e.minHeight);e.c.closest(".rev_slider_wrapper").css({height:f})}catch(d){console.log("Failure at Presize of Slider:"+d)}};setREVStartSize();var tpj=jQuery;var revapi10;tpj(document).ready(function(){if(tpj("#rev_slider_10_1").revolution==undefined){revslider_showDoubleJqueryError("#rev_slider_10_1");}else{revapi10=tpj("#rev_slider_10_1").show().revolution({sliderType:"",jsFileLocation:"//inwavethemes.com/wordpress/incharity/wp-content/plugins/revslider/public/assets/js/",sliderLayout:"fullscreen",dottedOverlay:"none",delay:7000,navigation:{keyboardNavigation:"off",keyboard_direction:"horizontal",mouseScrollNavigation:"off",mouseScrollReverse:"default",onHoverStop:"off",touch:{touchenabled:"on",swipe_threshold:75,swipe_min_touches:50,swipe_direction:"horizontal",drag_block_vertical:false},thumbnails:{style:"custom",enable:true,width:285,height:52,min_width:100,wrapper_padding:0,wrapper_color:"transparent",wrapper_opacity:"1",tmp:'<span class="tp-thumb-image"></span>',visibleAmount:5,hide_onmobile:false,hide_onleave:false,direction:"horizontal",span:false,position:"inner",space:0,h_align:"center",v_align:"bottom",h_offset:0,v_offset:50}},responsiveLevels:[1240,1024,778,480],visibilityLevels:[1240,1024,778,480],gridwidth:[1170,1024,767,479],gridheight:[625,600,500,400],lazyType:"smart",parallax:{type:"mouse",origo:"slidercenter",speed:2000,levels:[2,3,4,5,6,7,12,16,10,50,47,48,49,50,51,55],type:"mouse",},shadow:0,spinner:"off",stopLoop:"off",stopAfterLoops:-1,stopAtSlide:-1,shuffle:"off",autoHeight:"off",fullScreenAutoWidth:"off",fullScreenAlignForce:"off",fullScreenOffsetContainer:"",fullScreenOffset:"",disableProgressBar:"on",hideThumbsOnMobile:"off",hideSliderAtLimit:0,hideCaptionAtLimit:0,hideAllCaptionAtLilmit:0,startWithSlide:0,debugMode:false,fallbacks:{simplifyAll:"off",nextSlideOnWindowFocus:"off",disableFocusListener:false,}});}});</script>
    </div>
</div>